#!/bin/bash

user=$1
shift

for path in "$@"; do
    fspath=/eos/uscms/store/user/$user/croncopyeos/$path
    if [[ ! -d $fspath ]]; then
        >&2 echo $fspath does not exist
        exit 1
    fi
done

echo delete
for path in "$@"; do
    storepath=/store/user/$user/croncopyeos/$path
    eos root://cmseos.fnal.gov find -f $storepath | sed 's@/eos/uscms@@'
    eos root://cmseos.fnal.gov find -d $storepath | sed 's@^path=/eos/uscms@@' | perl -e 'print sort { length($b) <=> length($a) } <>'
done
